// This file is generated by running the atlas_builder.
package assets

/*
Note: This file assumes the existence of a type Rect that defines a rectangle in the same package, it can defined as:

	Rect :: rl.Rectangle

or if you don't use raylib:

	Rect :: struct {
		x, y, width, height: f32,
	}

or if you want to use integers (or any other numeric type):

	Rect :: struct {
		x, y, width, height: int,
	}

Just make sure you have something along those lines the same package as this file.
*/

TEXTURE_ATLAS_FILENAME :: "assets/atlas.png"
ATLAS_FONT_SIZE :: 32
LETTERS_IN_FONT :: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890?!&.,_:[]-+"

// A generated square in the atlas you can use with rl.SetShapesTexture to make
// raylib shapes such as rl.DrawRectangleRec() use the atlas.
SHAPES_TEXTURE_RECT :: Rect {67, 0, 10, 10}

Texture_Name :: enum {
	None,
	Border_Rounded,
	Border_Square,
	Logo,
}

Atlas_Texture :: struct {
	rect: Rect,
	// These offsets tell you how much space there is between the rect and the edge of the original document.
	// The atlas is tightly packed, so empty pixels are removed. This can be especially apparent in animations where
	// frames can have different offsets due to different amount of empty pixels around the frames.
	// In many cases you need to add {offset_left, offset_top} to your position. But if you are
	// flipping a texture, then you might need offset_bottom or offset_right.
	offset_top: f32,
	offset_right: f32,
	offset_bottom: f32,
	offset_left: f32,
	document_size: [2]f32,
	duration: f32,
	// 9-slice insets for scalable UI elements. Defines the center rect.
	// For non-9-slice textures, this defaults to the full texture rect.
	nine_slice: Rect,
}

atlas_textures: [Texture_Name]Atlas_Texture = {
	.None = {},
	.Border_Rounded = { rect = {0, 0, 18, 18}, offset_top = 0, offset_right = 582, offset_bottom = 362, offset_left = 0, document_size = {600, 380}, duration = 0.100, nine_slice = {2, 2, 14, 14} },
	.Border_Square = { rect = {19, 0, 18, 18}, offset_top = 0, offset_right = 582, offset_bottom = 362, offset_left = 0, document_size = {600, 380}, duration = 0.100, nine_slice = {2, 2, 14, 13} },
	.Logo = { rect = {38, 0, 28, 10}, offset_top = 0, offset_right = 572, offset_bottom = 370, offset_left = 0, document_size = {600, 380}, duration = 0.100, nine_slice = {0, 0, 28, 10} },
}

Animation_Name :: enum {
	None,
}

Tag_Loop_Dir :: enum {
	Forward,
	Reverse,
	Ping_Pong,
	Ping_Pong_Reverse,
}

// Any aseprite file with frames will create new animations. Also, any tags
// within the aseprite file will make that that into a separate animation.
Atlas_Animation :: struct {
	first_frame: Texture_Name,
	last_frame: Texture_Name,
	document_size: [2]f32,
	loop_direction: Tag_Loop_Dir,
	repeat: u16,
}

atlas_animations := [Animation_Name]Atlas_Animation {
	.None = {},
}

UI_COLOR_0 :: Color{0, 0, 0, 0}
UI_COLOR_1 :: Color{34, 32, 52, 255}
UI_COLOR_2 :: Color{69, 40, 60, 255}
UI_COLOR_3 :: Color{102, 57, 49, 255}
UI_COLOR_4 :: Color{143, 86, 59, 255}
UI_COLOR_5 :: Color{223, 113, 38, 255}
UI_COLOR_6 :: Color{217, 160, 102, 255}
UI_COLOR_7 :: Color{238, 195, 154, 255}
UI_COLOR_8 :: Color{251, 242, 54, 255}
UI_COLOR_9 :: Color{153, 229, 80, 255}
UI_COLOR_10 :: Color{106, 190, 48, 255}
UI_COLOR_11 :: Color{55, 148, 110, 255}
UI_COLOR_12 :: Color{75, 105, 47, 255}
UI_COLOR_13 :: Color{82, 75, 36, 255}
UI_COLOR_14 :: Color{50, 60, 57, 255}
UI_COLOR_15 :: Color{63, 63, 116, 255}
UI_COLOR_16 :: Color{48, 96, 130, 255}
UI_COLOR_17 :: Color{91, 110, 225, 255}
UI_COLOR_18 :: Color{99, 155, 255, 255}
UI_COLOR_19 :: Color{95, 205, 228, 255}
UI_COLOR_20 :: Color{203, 219, 252, 255}
UI_COLOR_21 :: Color{255, 255, 255, 255}
UI_COLOR_22 :: Color{155, 173, 183, 255}
UI_COLOR_23 :: Color{132, 126, 135, 255}
UI_COLOR_24 :: Color{105, 106, 106, 255}
UI_COLOR_25 :: Color{89, 86, 82, 255}
UI_COLOR_26 :: Color{118, 66, 138, 255}
UI_COLOR_27 :: Color{172, 50, 50, 255}
UI_COLOR_28 :: Color{217, 87, 99, 255}
UI_COLOR_29 :: Color{215, 123, 186, 255}
UI_COLOR_30 :: Color{143, 151, 74, 255}
UI_COLOR_31 :: Color{138, 111, 48, 255}

UI_PALETTE :: [32]Color{
	UI_COLOR_0,
	UI_COLOR_1,
	UI_COLOR_2,
	UI_COLOR_3,
	UI_COLOR_4,
	UI_COLOR_5,
	UI_COLOR_6,
	UI_COLOR_7,
	UI_COLOR_8,
	UI_COLOR_9,
	UI_COLOR_10,
	UI_COLOR_11,
	UI_COLOR_12,
	UI_COLOR_13,
	UI_COLOR_14,
	UI_COLOR_15,
	UI_COLOR_16,
	UI_COLOR_17,
	UI_COLOR_18,
	UI_COLOR_19,
	UI_COLOR_20,
	UI_COLOR_21,
	UI_COLOR_22,
	UI_COLOR_23,
	UI_COLOR_24,
	UI_COLOR_25,
	UI_COLOR_26,
	UI_COLOR_27,
	UI_COLOR_28,
	UI_COLOR_29,
	UI_COLOR_30,
	UI_COLOR_31,
}

Atlas_Glyph :: struct {
	rect: Rect,
	value: rune,
	offset_x: int,
	offset_y: int,
	advance_x: int,
}

atlas_glyphs: []Atlas_Glyph = {
}
