// This file is generated by running the atlas_builder.
package pxui

/*
Note: This file assumes the existence of a type Rect that defines a rectangle in the same package, it can defined as:

	Rect :: rl.Rectangle

or if you don't use raylib:

	Rect :: struct {
		x, y, width, height: f32,
	}

or if you want to use integers (or any other numeric type):

	Rect :: struct {
		x, y, width, height: int,
	}

Just make sure you have something along those lines the same package as this file.
*/

TEXTURE_ATLAS_FILENAME :: "assets/atlas.png"
ATLAS_FONT_SIZE :: 32
LETTERS_IN_FONT :: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890?!&.,_:[]-+"

// A generated square in the atlas you can use with rl.SetShapesTexture to make
// raylib shapes such as rl.DrawRectangleRec() use the atlas.
SHAPES_TEXTURE_RECT :: Rect {66, 0, 10, 10}

Texture_Name :: enum {
	None,
	Logo,
	Border_Square,
	Border_Rounded,
}

Atlas_Texture :: struct {
	rect: Rect,
	// These offsets tell you how much space there is between the rect and the edge of the original document.
	// The atlas is tightly packed, so empty pixels are removed. This can be especially apparent in animations where
	// frames can have different offsets due to different amount of empty pixels around the frames.
	// In many cases you need to add {offset_left, offset_top} to your position. But if you are
	// flipping a texture, then you might need offset_bottom or offset_right.
	offset_top: f32,
	offset_right: f32,
	offset_bottom: f32,
	offset_left: f32,
	document_size: [2]f32,
	duration: f32,
	// 9-slice insets for scalable UI elements. Defines the center rect that can be stretched.
	// For non-9-slice textures, this defaults to the full texture rect.
	nine_slice: Rect,
}

atlas_textures: [Texture_Name]Atlas_Texture = {
	.None = {},
	.Logo = { rect = {38, 0, 27, 10}, offset_top = 0, offset_right = 573, offset_bottom = 370, offset_left = 0, document_size = {600, 380}, duration = 0.100, nine_slice = {0, 0, 27, 10} },
	.Border_Square = { rect = {0, 0, 18, 18}, offset_top = 0, offset_right = 582, offset_bottom = 362, offset_left = 0, document_size = {600, 380}, duration = 0.100, nine_slice = {2, 2, 14, 14} },
	.Border_Rounded = { rect = {19, 0, 18, 18}, offset_top = 0, offset_right = 582, offset_bottom = 362, offset_left = 0, document_size = {600, 380}, duration = 0.100, nine_slice = {2, 2, 14, 14} },
}

Animation_Name :: enum {
	None,
}

Tag_Loop_Dir :: enum {
	Forward,
	Reverse,
	Ping_Pong,
	Ping_Pong_Reverse,
}

// Any aseprite file with frames will create new animations. Also, any tags
// within the aseprite file will make that that into a separate animation.
Atlas_Animation :: struct {
	first_frame: Texture_Name,
	last_frame: Texture_Name,
	document_size: [2]f32,
	loop_direction: Tag_Loop_Dir,
	repeat: u16,
}

atlas_animations := [Animation_Name]Atlas_Animation {
	.None = {},
}

Atlas_Glyph :: struct {
	rect: Rect,
	value: rune,
	offset_x: int,
	offset_y: int,
	advance_x: int,
}

atlas_glyphs: []Atlas_Glyph = {
}
